<a href="https://colab.research.google.com/github/TyamanovaMargo/DI-Bootcamp/blob/main/ExercisesXP_Week4_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#🌟 Exercise 1 : Array Creation and

<p>Create a 1D NumPy array containing numbers from 0 to 9</p>



In [2]:
import numpy as np

# Creating a 1D array
array = np.arange(0, 10)  # Array of numbers from 0 to 9

print(array)

[0 1 2 3 4 5 6 7 8 9]


#🌟 Exercise 2 : Type Conversion and Array Operations

Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

In [6]:
array_1d = np.array([3.14, 2.17, 0, 1, 2])
print(array_1d)

arr = np.array(array_1d, dtype=int)

print(arr)
print(arr.dtype)

[3.14 2.17 0.   1.   2.  ]
[3 2 0 1 2]
int64


#🌟 Exercise 3 : Working with Multi-Dimensional Arrays
Create a 3x3 NumPy array with values ranging from 1 to 9.

In [10]:
# array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8, 9]]])
import numpy as np

array_3d = np.arange(1, 10).reshape(3, 3, 1)


print(array_3d)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


#🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers

Create a 2D NumPy array of shape (4, 5) filled with random numbers.

In [14]:
import numpy as np

array_2d = np.random.rand(4,5)
around_array2d = np.around(array_2d, 2) # just 2 symbols after dot
print(around_array2d)




[[0.34 0.55 0.8  0.63 0.94]
 [0.63 0.49 0.6  0.39 0.63]
 [0.81 0.14 0.09 0.97 0.08]
 [0.78 0.21 0.26 0.08 0.93]]


#🌟 Exercise 5 : Indexing Arrays
Select the second row from a given 2D NumPy array.

In [17]:
import numpy as np

array = np.array([[21, 22, 23, 22, 22],
                  [20, 21, 22, 23, 24],
                  [21, 22, 23, 22, 22]])

second_row = array[1]
print( second_row)



[20 21 22 23 24]


#🌟 Exercise 6 : Reversing elements
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [20]:
array_1d = np.array([0, 8, 7, 6, 5, 4, 3, 2, 1, 9])

# reversed_arr_1d = np.flip(array_1d) # using func flip
reversed_arr_1d = array_1d[::-1]  # or slising

print(reversed_arr_1d)





[9 1 2 3 4 5 6 7 8 0]


#🌟 Exercise 7 : Identity Matrix

In [25]:
import numpy as np

identity_matrix = np.eye(4)
print(identity_matrix)







[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#🌟 Exercise 8 : Simple Aggregate Funcs

In [27]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

sum_of_arr = np.sum(array_1d)
avg_of_arr = np.mean(array_1d)

print(sum_of_arr, avg_of_arr)


45 5.0


#🌟 Exercise 9 : Create Array and Change its Structure

Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [32]:
array = np.arange(1,21)
print(array)

reshaped_arr = array.reshape(4,5)
print(reshaped_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


#🌟 Exercise 10 : Conditional Selection of Values

In [34]:
array = np.arange(1,11)
odd_extract_array =  array[array % 2 != 0]

print(odd_extract_array)

[1 3 5 7 9]
